### ISSUE TITLE
Limit Ignored

### ISSUE THREAD

**Issue by matrixdevuk** [PaulBender/Username-Change-Approval-Limit-and-History#4]
I set the limit for my administrator group to 0 and 0 so that I could get completely unlimited changes and no restrictions on my admin account, and I get this message:

> You must wait a minimum of 6 hours before you can change your username again.

Please could you either suggest a problem I am making or fix it?

**Comment by PaulBender** [comment]
There's a setting that controls the minimum wait time between username changes. You'll need to change that setting to 0 in order to have truly unlimited changes.

The setting is called **Minimum Time Between Username Changes** and it's located under the **Login and Registration Options** setting group

**Comment by matrixdevuk** [comment]
Ah, I see it!
Thank you very much.
